### ISSUE TITLE
Swiper issue ... 

### ISSUE THREAD

**Issue by stuartrapop** [appinioGmbH/flutter_packages#180]
I am getting the following errors when I swipe cards very fast. The widget continues to seem to work so far. Any ideas ? 

To give context, after each swipe I fully rebuild the swiper via a consumer because my list must be updated after each swipe to take into account all selected items. It's not elegant, but it works! 

```
Another exception was thrown: _AppinioSwiperState#b7a39(ticker active) was disposed with an active Ticker.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4833 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4833 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4833 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
```

**Comment by bilalhamud** [comment]
Fixed with version 2.1.0

**Comment by stuartrapop** [comment]
Hello,

Bravo for the latest update. It is really cool to have the controller state exposed for animations. 

  I still get this issue with the latest version - although it does not seem to be causing any issues for me. 
```

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4833 pos 12: '_lifecycleState !=
_ElementLifecycle.defunct': is not true.
E/flutter ( 8174): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4833 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
E/flutter ( 8174): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 8174): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 8174): #2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4833:12)
E/flutter ( 8174): #3      State.setState (package:flutter/src/widgets/framework.dart:1158:15)
E/flutter ( 8174): #4      _AppinioSwiperState._startActivity (package:appinio_swiper/appinio_swiper.dart:278:5)
E/flutter ( 8174): <asynchronous suspension>
E/flutter ( 8174): #5      _AppinioSwiperState._onSwipe (package:appinio_swiper/appinio_swiper.dart:194:5)
E/flutter ( 8174): <asynchronous suspension>
```
